name: Compile and publish pdfs on Github pages

env:
    GH_TOKEN: ${{ github.token }}

on: 
  push:
    branch:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup typst
        uses: typst-community/setup-typst@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './public/package-lock.json'

      - name: Compile documents into dist directory
        run: ./compile.sh --disable-sans-math

      - name: Fetch fb-cli binary
        run: gh release download -p fb-cli -R viandoxdev/flashbang

      - name: Make fb-cli executable
        run: chmod +x ./fb-cli

      - name: Bundle cards data
        run: ./bundle-data.sh

      - name: Fetch fb-web wasm bundle
        run: gh release download -p wasm-bundle.zip -R viandoxdev/flashbang -D ./public

      - name: Setup cache buster from commit SHA
        run: echo "PUBLIC_CACHE_BUSTER=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build site
        working-directory: ./public
        run: make build
        env: 
          BASE_PATH: '/fb-cards'

      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/build
          publish_branch: gh-pages
